--- 
abstract: perl module to detect favicon url
author: Daisuke Murase <typester@cpan.org>
build_requires: 
  Test::MockObject::Extends: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Favicon
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Exporter: 0
  HTML::ResolveLink: 0
  HTML::TreeBuilder: 0
  LWP::UserAgent: 0
version: 0.02
